# Generated by Django 4.2.16 on 2024-11-26 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="feature_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
